// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi;

#nullable disable

namespace WebApiMigrations
{
    [DbContext(typeof(Context))]
    [Migration("20241009215021_startedDateUpdate")]
    partial class startedDateUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95d3041f-f142-4409-b592-e19e4e7028f9"),
                            Created = new DateTime(2024, 10, 17, 21, 50, 20, 778, DateTimeKind.Utc).AddTicks(9743),
                            Description = "Desc1",
                            Title = "Title1"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a812867f-b8e9-4835-896e-8fb6099b4621"),
                            Sum = 0m,
                            UserId = new Guid("6135f7e8-761b-461d-b975-d099c4fb455a")
                        },
                        new
                        {
                            Id = new Guid("79b58660-1d78-4976-a98c-b29b4a57cac4"),
                            Sum = 0m,
                            UserId = new Guid("76302cb6-2487-4fbc-8de1-934a51d06783")
                        },
                        new
                        {
                            Id = new Guid("8a48c13f-c50e-42fa-8e2b-2357548d09f5"),
                            Sum = 0m,
                            UserId = new Guid("c468a92f-3bdc-4035-82e8-87bfe26ae2e2")
                        },
                        new
                        {
                            Id = new Guid("05d4b664-b567-412d-a21b-7824c0976206"),
                            Sum = 0m,
                            UserId = new Guid("d191ab87-3e56-4c2c-a195-bffe56542d84")
                        },
                        new
                        {
                            Id = new Guid("fa78ddf5-b4a5-4d31-94a9-58a25dc6fc3b"),
                            Sum = 0m,
                            UserId = new Guid("f38cda8e-d1ca-4e60-be2d-fbca58f4edbe")
                        },
                        new
                        {
                            Id = new Guid("a9f5f4c3-415d-464c-a532-03302b378b0c"),
                            Sum = 0m,
                            UserId = new Guid("6865fe79-462a-453f-ace5-7b56308827cc")
                        },
                        new
                        {
                            Id = new Guid("4150c4a8-9a7b-4c87-97e3-fad1cfed1c39"),
                            Sum = 0m,
                            UserId = new Guid("60b358fc-e826-4563-a432-3646a984bc55")
                        },
                        new
                        {
                            Id = new Guid("1365566a-563a-4834-b7f6-950297794793"),
                            Sum = 0m,
                            UserId = new Guid("d9d0189b-c971-4811-94d7-eb1349015c7c")
                        },
                        new
                        {
                            Id = new Guid("9e7ab212-a9d6-4616-86e1-fb842485f598"),
                            Sum = 0m,
                            UserId = new Guid("06f842a9-751d-4010-b535-85737f345ccf")
                        },
                        new
                        {
                            Id = new Guid("90fb9e61-6850-4ff7-8c18-9d5fd70b0c77"),
                            Sum = 0m,
                            UserId = new Guid("19f0034c-fac8-494d-a640-be26fd8f4916")
                        },
                        new
                        {
                            Id = new Guid("d12edc6f-8952-44b7-acaa-7f050c50bc04"),
                            Sum = 0m,
                            UserId = new Guid("c07d30eb-94ad-4ae9-abf5-d43991aca43c")
                        });
                });

            modelBuilder.Entity("WebApi.Models.OrderProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0af06de-6202-4ed9-866a-79475ca9efa8"),
                            Count = 1,
                            Name = "Цифровой арт \"Далекое будущее\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("3825d84a-447f-4217-91ee-9f9a60e6f63d"),
                            Count = 1,
                            Name = "Видеоурок \"Как сделать первый 3D дизайн\"",
                            Price = 2000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("ce616c21-51ac-4660-9aef-cfd65e3014e3"),
                            Count = 1,
                            Name = "Курс \"Художник за месяц\"",
                            Price = 6000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("b2bd8a05-d8aa-4a1c-bbf8-202fa0f8acc8"),
                            Count = 1,
                            Name = "Песня, сгенерированная нейросетью",
                            Price = 100m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("1405b1eb-51d3-4750-85f6-6f4636967f23"),
                            Count = 1,
                            Name = "Цифровой арт \"Цифровое искусство\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("b428d92f-06f7-49d4-b984-b396d9533982"),
                            Count = 1,
                            Name = "Видеоурок \"Песня \"Ромашки\" на гитаре\"",
                            Price = 2000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("e7cfd964-05de-432b-8068-7de98e434d4a"),
                            Count = 1,
                            Name = "Цифровой арт \"Красивый город\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("ee1a693f-99d8-4afd-a4c8-4d60db28bf10"),
                            Count = 1,
                            Name = "Реклама",
                            Price = 10000m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("d5745193-0e24-445e-9e95-60220b194d42"),
                            Count = 1,
                            Name = "Помощь с идеей для вашего проекта",
                            Price = 500m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("692ccf87-b5a2-4dc1-ab46-b104dd46ae1c"),
                            Count = 1,
                            Name = "Онлайн урок по рисованию",
                            Price = 1900m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("e43f7445-fad5-4534-b01d-50d8096f82d2"),
                            Count = 1,
                            Name = "Цифровой арт \"Ночной город\"",
                            Price = 3500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("8281f531-9ec9-44cc-98e4-fc7af383488c"),
                            Count = 1,
                            Name = "Видеоурок \"Основы 3D моделирования\"",
                            Price = 2500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("d5641a58-80fe-4bc0-b7d1-58ecfb85475d"),
                            Count = 1,
                            Name = "Курс \"Графика в игре\"",
                            Price = 4500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("65adcb24-538b-4e8c-a860-70442495dda8"),
                            Count = 1,
                            Name = "Песня, сгенерированная нейросетью \"Весна\"",
                            Price = 150m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("a381fc31-eaee-481c-868f-a88f9fef1749"),
                            Count = 1,
                            Name = "Цифровой арт \"Закат на пляже\"",
                            Price = 4000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("43231c9a-3418-4726-84a9-fd2c6f84c9de"),
                            Count = 1,
                            Name = "Курс \"3D анимация\"",
                            Price = 6000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("408d5260-a49c-46d2-8114-eb24d0bfb424"),
                            Count = 1,
                            Name = "Цифровой арт \"Летний день\"",
                            Price = 2000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("a7eb1467-1682-4bea-80f4-6dba64d3ad30"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Photoshop\"",
                            Price = 1500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("827e8080-b986-4825-a326-a5aed79d134f"),
                            Count = 1,
                            Name = "Цифровой арт \"Зимний лес\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("06f79e87-ddf3-4c49-92b2-cc356f85b646"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование портретов\"",
                            Price = 3000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("564663ac-3011-4cf9-90fe-9300020b476e"),
                            Count = 1,
                            Name = "Курс \"2D анимация\"",
                            Price = 4000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("8e4f259c-007c-4aac-b771-cb57e608d731"),
                            Count = 1,
                            Name = "Цифровой арт \"Городской пейзаж\"",
                            Price = 2500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("bab26e79-6c90-449c-9038-dbe258b975de"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Procreate\"",
                            Price = 3500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("9287dc76-18bc-4002-b5e6-19deb1d77a6c"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с водопадом\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("1342ffba-e85b-45a1-a1b5-404dc1986e25"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Illustrator\"",
                            Price = 2000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("0ff9f2f2-cb34-4c57-8a96-32655cd1da37"),
                            Count = 1,
                            Name = "Курс \"3D моделирование\"",
                            Price = 4500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("b70c166f-9069-4230-8d97-2fb2e667ae32"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с горами\"",
                            Price = 3000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("37265ae9-33b2-44ad-99b1-c549fcc5bc9b"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с озером\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("75aa912e-4315-482a-9c5a-184bf9a1e2bc"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Sketchbook\"",
                            Price = 3000m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("f638aca2-7890-4e7f-b1dd-f88145354069"),
                            Count = 1,
                            Name = "Курс \"2D игровая графика\"",
                            Price = 4000m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("01d885f7-7881-471e-a3e2-d4fcfcfe0210"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с лесом\"",
                            Price = 2500m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("e21788ac-9fa4-4474-9a9b-845229805542"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Affinity Designer\"",
                            Price = 3500m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("a50bbd30-e7c4-4a32-80f2-4edee9b2adb3"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с морем\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("d08768f0-1654-449d-bcfd-97a8f6e6794c"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Krita\"",
                            Price = 2000m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("f4993ba6-8ac3-46c3-af81-d4bb1d8fb2b9"),
                            Count = 1,
                            Name = "Курс \"3D игровая графика\"",
                            Price = 4500m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("a3c6de5f-7f87-4101-90b4-501fecb36f9b"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с пустыней\"",
                            Price = 3000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        },
                        new
                        {
                            Id = new Guid("a28f1b4b-2b83-4e30-af18-38af58d89dbc"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в PaintTool SAI\"",
                            Price = 2500m,
                            TypeId = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52")
                        },
                        new
                        {
                            Id = new Guid("0d478767-6694-445e-8bf2-f6712147e534"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с вулканом\"",
                            Price = 5000m,
                            TypeId = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4")
                        });
                });

            modelBuilder.Entity("WebApi.Models.TypeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffba678c-7f98-47db-b8fd-aa371c5efaf4"),
                            Name = "Товар"
                        },
                        new
                        {
                            Id = new Guid("b15898a5-fd66-4ec8-b65a-bc196889db52"),
                            Name = "Услуга"
                        });
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClient")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvider")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6135f7e8-761b-461d-b975-d099c4fb455a"),
                            Discount = 0m,
                            FIO = "Юриков Дмитрий Александрович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("76302cb6-2487-4fbc-8de1-934a51d06783"),
                            Discount = 0m,
                            FIO = "Иванов Сергей Максимович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("c468a92f-3bdc-4035-82e8-87bfe26ae2e2"),
                            Discount = 0m,
                            FIO = "Петров Алексей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("d191ab87-3e56-4c2c-a195-bffe56542d84"),
                            Discount = 0m,
                            FIO = "Сидоров Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("f38cda8e-d1ca-4e60-be2d-fbca58f4edbe"),
                            Discount = 0m,
                            FIO = "Морозов Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("6865fe79-462a-453f-ace5-7b56308827cc"),
                            Discount = 0m,
                            FIO = "Васильев Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("60b358fc-e826-4563-a432-3646a984bc55"),
                            Discount = 0m,
                            FIO = "Козлов Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("d9d0189b-c971-4811-94d7-eb1349015c7c"),
                            Discount = 0m,
                            FIO = "Новиков Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("06f842a9-751d-4010-b535-85737f345ccf"),
                            Discount = 0m,
                            FIO = "Соколов Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("19f0034c-fac8-494d-a640-be26fd8f4916"),
                            Discount = 0m,
                            FIO = "Михайлов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("c07d30eb-94ad-4ae9-abf5-d43991aca43c"),
                            Discount = 0m,
                            FIO = "Федоров Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("4575172b-166e-43e3-af4a-7da6467ce14f"),
                            Discount = 0m,
                            FIO = "Попов Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("3c7a9896-e818-4a6a-8a95-1b516a82629c"),
                            Discount = 0m,
                            FIO = "Лебедев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("94f57503-66c8-4a10-ae03-da99f5aff486"),
                            Discount = 0m,
                            FIO = "Ковалев Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("691cdc0c-8c16-4868-b587-cb9b6fd16127"),
                            Discount = 0m,
                            FIO = "Ильин Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("1dcc42a9-0724-4b3d-b8f9-c2699d06cb4d"),
                            Discount = 0m,
                            FIO = "Григорьев Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("364463f4-baab-40a8-8f2c-9cf77982ce6c"),
                            Discount = 0m,
                            FIO = "Семенов Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("5f9caa01-4356-4969-92f8-b6d622f048e5"),
                            Discount = 0m,
                            FIO = "Павлов Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("43da0b64-8ff9-40f2-8d97-1d539b9383af"),
                            Discount = 0m,
                            FIO = "Андреев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("e533be64-c1ac-41fa-80a6-529a36163087"),
                            Discount = 0m,
                            FIO = "Макаров Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("245836ac-2412-4fe1-9548-304daaa1cf9e"),
                            Discount = 0m,
                            FIO = "Николаев Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("738e28cf-42ce-406c-b67e-9cab59d29df3"),
                            Discount = 0m,
                            FIO = "Орлов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("1ebf0e54-9a35-4a10-9054-b81d1d75922f"),
                            Discount = 0m,
                            FIO = "Алексеев Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("d503a950-406f-459d-a690-3bbce73c08f7"),
                            Discount = 0m,
                            FIO = "Сергеев Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("8cf4937e-fb42-4e21-a26f-2b05876f2cea"),
                            Discount = 0m,
                            FIO = "Дмитриев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("b4c39c74-cb8b-46b7-a53d-103e2275de53"),
                            Discount = 0m,
                            FIO = "Егоров Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("67daab92-b483-47b4-b8c5-6ed905828fbf"),
                            Discount = 0m,
                            FIO = "Кузнецов Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("be99cca3-1228-461f-af6e-69dbc6d590d9"),
                            Discount = 0m,
                            FIO = "Борисов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("39cc6d32-cf9f-40df-a65f-87bce06befa5"),
                            Discount = 0m,
                            FIO = "Соловьев Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("36dabd14-217f-4917-a281-8ac4dbdb842f"),
                            Discount = 0m,
                            FIO = "Комаров Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("2c8def36-64e6-477d-8f35-76fc892423a4"),
                            Discount = 0m,
                            FIO = "Белов Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("80c4bf1d-a15d-40ac-8293-007a04c79b31"),
                            Discount = 0m,
                            FIO = "Филиппов Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("61b98779-5bfe-45eb-995b-1688e2aadd6a"),
                            Discount = 0m,
                            FIO = "Матвеев Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        });
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.HasOne("WebApi.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Models.OrderProducts", b =>
                {
                    b.HasOne("WebApi.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.HasOne("WebApi.Models.TypeProduct", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeProduct");
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.TypeProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
