// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi;

#nullable disable

namespace WebApiMigrations
{
    [DbContext(typeof(Context))]
    [Migration("20241009220234_startedDateUpdateV2")]
    partial class startedDateUpdateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58339ca1-5e56-4851-b422-234649f6472f"),
                            Created = new DateTime(2024, 10, 30, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4212),
                            Description = "Выставка представляет работы современных художников, посвященные теме абстракции.",
                            Title = "Выставка современного искусства 'Абстракция'"
                        },
                        new
                        {
                            Id = new Guid("36eb092e-05fd-41d6-bc62-51940137893a"),
                            Created = new DateTime(2024, 11, 7, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4230),
                            Description = "Конкурс открыт для художников со всего мира. Прием работ до 15 октября.",
                            Title = "Международный конкурс 'Живопись 2023'"
                        },
                        new
                        {
                            Id = new Guid("d7e6e1bc-f58e-4069-ab22-d8223c323e31"),
                            Created = new DateTime(2024, 10, 12, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4233),
                            Description = "Выставка посвящена искусству XX века, включая работы известных мастеров.",
                            Title = "Выставка 'Искусство XX века'"
                        },
                        new
                        {
                            Id = new Guid("d7da9d3b-ea39-483f-92c7-8ab2e57c4304"),
                            Created = new DateTime(2024, 10, 16, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4239),
                            Description = "Конкурс для молодых художников до 30 лет. Прием работ до 30 ноября.",
                            Title = "Конкурс 'Молодое искусство'"
                        },
                        new
                        {
                            Id = new Guid("4c2180a0-afed-4e62-8544-2a8626c88af2"),
                            Created = new DateTime(2024, 11, 2, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4242),
                            Description = "Выставка фотографий, демонстрирующих фотографию как самостоятельное искусство.",
                            Title = "Выставка 'Фотография как искусство'"
                        },
                        new
                        {
                            Id = new Guid("ac89a8a0-83a5-46f3-8cb7-35e6baa2f2f5"),
                            Created = new DateTime(2024, 10, 25, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4245),
                            Description = "Конкурс посвящен графике и рисункам. Прием работ до 20 декабря.",
                            Title = "Конкурс 'Графика и рисунки'"
                        },
                        new
                        {
                            Id = new Guid("e64c3e83-009e-4134-b302-2f313d78ab01"),
                            Created = new DateTime(2024, 10, 18, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4248),
                            Description = "Выставка работ художников из стран Востока, представляющих традиционное и современное искусство.",
                            Title = "Выставка 'Искусство Востока'"
                        },
                        new
                        {
                            Id = new Guid("21a1ff8a-58d0-41e5-be60-9d9070d2e10b"),
                            Created = new DateTime(2024, 11, 4, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4251),
                            Description = "Конкурс для скульпторов и художников, работающих в области пластики. Прием работ до 10 января.",
                            Title = "Конкурс 'Скульптура и пластика'"
                        },
                        new
                        {
                            Id = new Guid("d254605c-74c6-438c-92f3-d7294a5c158a"),
                            Created = new DateTime(2024, 10, 13, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4254),
                            Description = "Выставка, демонстрирующая взаимодействие искусства и современных технологий.",
                            Title = "Выставка 'Искусство и технологии'"
                        },
                        new
                        {
                            Id = new Guid("de8a49bc-897b-4fa9-aa42-bf26b1667138"),
                            Created = new DateTime(2024, 11, 1, 22, 2, 34, 277, DateTimeKind.Utc).AddTicks(4258),
                            Description = "Конкурс для детских художников до 12 лет. Прием работ до 1 февраля.",
                            Title = "Конкурс 'Искусство для детей'"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d8e73c5-d853-4f1e-92ab-d5cc5f84c5a9"),
                            Sum = 0m,
                            UserId = new Guid("5ba1051a-f926-4232-b868-c419393fc3db")
                        },
                        new
                        {
                            Id = new Guid("82a58195-2111-47a5-a66f-e3c8fc11cba6"),
                            Sum = 0m,
                            UserId = new Guid("b64ecc03-31c9-42f7-8b03-c962f2b71626")
                        },
                        new
                        {
                            Id = new Guid("ab2239d0-e8b2-4011-bbd3-da430e8a6852"),
                            Sum = 0m,
                            UserId = new Guid("585ac79f-b7a0-4628-9b04-ca206f7789c8")
                        },
                        new
                        {
                            Id = new Guid("d55e04e8-b332-4909-8a60-b1bb0ca3693c"),
                            Sum = 0m,
                            UserId = new Guid("3a9cda25-aa61-4af5-92a6-efcc92c0cd37")
                        },
                        new
                        {
                            Id = new Guid("6b8168f8-4cac-4643-9ccf-1e708c935a49"),
                            Sum = 0m,
                            UserId = new Guid("9d48fe50-2a4d-4f45-a3cc-ab52bb89f2b1")
                        },
                        new
                        {
                            Id = new Guid("56be3227-f305-49d5-b333-079b24494165"),
                            Sum = 0m,
                            UserId = new Guid("4686a4b7-4854-4a7a-9353-189c5f7e4389")
                        },
                        new
                        {
                            Id = new Guid("da3667ba-fab2-4026-bac0-7f2c94523b6d"),
                            Sum = 0m,
                            UserId = new Guid("092ae16c-9cf9-4e90-b177-50ecb2e3910d")
                        },
                        new
                        {
                            Id = new Guid("927c67df-1f62-4162-919f-f8405a43b7d6"),
                            Sum = 0m,
                            UserId = new Guid("d4799574-0cf1-452d-ad7d-7ab94e199ab9")
                        },
                        new
                        {
                            Id = new Guid("779f3978-6ddc-4a7a-86c6-06e1339bea1e"),
                            Sum = 0m,
                            UserId = new Guid("6cfe1b90-e5bd-4c55-9623-72f12a9f8d43")
                        },
                        new
                        {
                            Id = new Guid("e36468b9-8f81-4bdd-bf25-598eaf02e48c"),
                            Sum = 0m,
                            UserId = new Guid("40f089ab-0289-4ec8-94b6-d25e932332b3")
                        },
                        new
                        {
                            Id = new Guid("49f9f13f-980b-4657-9318-a210551e4648"),
                            Sum = 0m,
                            UserId = new Guid("082221a6-6b47-4493-8412-2f328a21977e")
                        });
                });

            modelBuilder.Entity("WebApi.Models.OrderProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92e95b48-9d7a-40fa-8c59-7cfacd720780"),
                            Count = 1,
                            Name = "Цифровой арт \"Далекое будущее\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("83fcb507-6b78-4096-9006-db626f1a21df"),
                            Count = 1,
                            Name = "Видеоурок \"Как сделать первый 3D дизайн\"",
                            Price = 2000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("765f4300-ad81-4d02-b297-99c38f08bc87"),
                            Count = 1,
                            Name = "Курс \"Художник за месяц\"",
                            Price = 6000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("f2df1f9f-b66c-4b33-81ad-3b80f9a54abd"),
                            Count = 1,
                            Name = "Песня, сгенерированная нейросетью",
                            Price = 100m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("1cf02577-ca5f-4411-9907-d13c4c970356"),
                            Count = 1,
                            Name = "Цифровой арт \"Цифровое искусство\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("a50a9ef6-14f3-4b01-8df6-d83adfa38442"),
                            Count = 1,
                            Name = "Видеоурок \"Песня \"Ромашки\" на гитаре\"",
                            Price = 2000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("f2ac61ab-95b8-44c2-aaa3-a9984671bfcc"),
                            Count = 1,
                            Name = "Цифровой арт \"Красивый город\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("ab5f37f9-54c0-4a77-8f70-2f7db77a0b7b"),
                            Count = 1,
                            Name = "Реклама",
                            Price = 10000m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("7fd7bc37-1937-4867-bfb5-c7043e50c257"),
                            Count = 1,
                            Name = "Помощь с идеей для вашего проекта",
                            Price = 500m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("f07eb676-2fa4-4cec-959a-08fa2b670b73"),
                            Count = 1,
                            Name = "Онлайн урок по рисованию",
                            Price = 1900m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("2db81b6d-e3fc-462b-bdbb-2aa4763fe5b1"),
                            Count = 1,
                            Name = "Цифровой арт \"Ночной город\"",
                            Price = 3500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("18bb9847-1633-46c4-b8cf-4a60c57ab10f"),
                            Count = 1,
                            Name = "Видеоурок \"Основы 3D моделирования\"",
                            Price = 2500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("b9736cff-3b96-4680-bddb-7c822cec5358"),
                            Count = 1,
                            Name = "Курс \"Графика в игре\"",
                            Price = 4500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("fe5a98cc-5bc7-40d9-a30d-e124e7d4dc9c"),
                            Count = 1,
                            Name = "Песня, сгенерированная нейросетью \"Весна\"",
                            Price = 150m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("bd7e0876-29b7-44dc-b2b1-690f1abfe78d"),
                            Count = 1,
                            Name = "Цифровой арт \"Закат на пляже\"",
                            Price = 4000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("99b49d0f-1855-4f91-81da-92c13cae73af"),
                            Count = 1,
                            Name = "Курс \"3D анимация\"",
                            Price = 6000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("5596e107-0997-4f22-9db0-98b311a24dfc"),
                            Count = 1,
                            Name = "Цифровой арт \"Летний день\"",
                            Price = 2000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("a46317b3-3ef1-4e42-97d9-0dbb0a58d5e0"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Photoshop\"",
                            Price = 1500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("87f97c00-9396-490c-8556-4b97fb379998"),
                            Count = 1,
                            Name = "Цифровой арт \"Зимний лес\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("e8d2ba41-7cd0-46bd-8e29-f2e127a9114f"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование портретов\"",
                            Price = 3000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("8c438b4b-8157-412c-b9c4-f89e0a11a277"),
                            Count = 1,
                            Name = "Курс \"2D анимация\"",
                            Price = 4000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("f75d397b-36ae-4c3e-a5a1-042f5fdc57a2"),
                            Count = 1,
                            Name = "Цифровой арт \"Городской пейзаж\"",
                            Price = 2500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("feab2179-c234-4960-86bf-17f7e4089aac"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Procreate\"",
                            Price = 3500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("cf43902d-2ab4-43ce-9611-8713c815db53"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с водопадом\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("ff652fb8-a33c-4fce-ace3-6926817f17bc"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Illustrator\"",
                            Price = 2000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("6cc9107c-1d36-46b7-accd-9251a797a4a0"),
                            Count = 1,
                            Name = "Курс \"3D моделирование\"",
                            Price = 4500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("823f309b-992e-4f9f-9a4c-eff8b0e54f49"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с горами\"",
                            Price = 3000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("dd38a027-0bf4-48d2-8cbb-6ff8e5ba463e"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с озером\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("6abd137c-f131-431a-accc-a9e362be39e2"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Sketchbook\"",
                            Price = 3000m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("a32633fe-9f8f-4559-aff4-924ae6a3ad4e"),
                            Count = 1,
                            Name = "Курс \"2D игровая графика\"",
                            Price = 4000m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("4630792d-fd9e-4ac8-94a9-f2f8dac0ea59"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с лесом\"",
                            Price = 2500m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("bf3b962d-e34d-4462-a1a4-9274507ae5e1"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Affinity Designer\"",
                            Price = 3500m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("8524858d-1d5a-42d5-acc6-c7260277ea8b"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с морем\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("38b7cf5f-0f52-4a05-85be-f6ce02821e2f"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Krita\"",
                            Price = 2000m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("00372f81-ebef-43ef-ac2d-5619969822c0"),
                            Count = 1,
                            Name = "Курс \"3D игровая графика\"",
                            Price = 4500m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("244fff05-1912-49a6-be38-d94e3611a743"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с пустыней\"",
                            Price = 3000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        },
                        new
                        {
                            Id = new Guid("e7009ac0-865c-4b51-b5dc-37dbae7b615b"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в PaintTool SAI\"",
                            Price = 2500m,
                            TypeId = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228")
                        },
                        new
                        {
                            Id = new Guid("22998821-fb2e-4141-ac72-3385af29f60a"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с вулканом\"",
                            Price = 5000m,
                            TypeId = new Guid("f56906c9-6721-4c98-9560-bd9113e43584")
                        });
                });

            modelBuilder.Entity("WebApi.Models.TypeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f56906c9-6721-4c98-9560-bd9113e43584"),
                            Name = "Товар"
                        },
                        new
                        {
                            Id = new Guid("fa0914dc-0673-46e9-a306-1fc33e316228"),
                            Name = "Услуга"
                        });
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClient")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvider")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ba1051a-f926-4232-b868-c419393fc3db"),
                            Discount = 0m,
                            FIO = "Юриков Дмитрий Александрович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("b64ecc03-31c9-42f7-8b03-c962f2b71626"),
                            Discount = 0m,
                            FIO = "Иванов Сергей Максимович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("585ac79f-b7a0-4628-9b04-ca206f7789c8"),
                            Discount = 0m,
                            FIO = "Петров Алексей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("3a9cda25-aa61-4af5-92a6-efcc92c0cd37"),
                            Discount = 0m,
                            FIO = "Сидоров Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("9d48fe50-2a4d-4f45-a3cc-ab52bb89f2b1"),
                            Discount = 0m,
                            FIO = "Морозов Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("4686a4b7-4854-4a7a-9353-189c5f7e4389"),
                            Discount = 0m,
                            FIO = "Васильев Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("092ae16c-9cf9-4e90-b177-50ecb2e3910d"),
                            Discount = 0m,
                            FIO = "Козлов Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("d4799574-0cf1-452d-ad7d-7ab94e199ab9"),
                            Discount = 0m,
                            FIO = "Новиков Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("6cfe1b90-e5bd-4c55-9623-72f12a9f8d43"),
                            Discount = 0m,
                            FIO = "Соколов Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("40f089ab-0289-4ec8-94b6-d25e932332b3"),
                            Discount = 0m,
                            FIO = "Михайлов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("082221a6-6b47-4493-8412-2f328a21977e"),
                            Discount = 0m,
                            FIO = "Федоров Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("3c953c26-f702-4c92-bab2-01b0198b2bee"),
                            Discount = 0m,
                            FIO = "Попов Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("d0e7795e-6770-4f34-9a57-5fbeecd5d475"),
                            Discount = 0m,
                            FIO = "Лебедев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("8f6c17af-edc7-4501-a8c0-23bdb6afa0d9"),
                            Discount = 0m,
                            FIO = "Ковалев Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("2d3694cb-398a-4165-a12b-55b725582c21"),
                            Discount = 0m,
                            FIO = "Ильин Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("38f3e1f4-15b0-458b-9025-bc211d9cc09d"),
                            Discount = 0m,
                            FIO = "Григорьев Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("e782e27f-1cef-4e37-9327-65ff262a1dea"),
                            Discount = 0m,
                            FIO = "Семенов Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("6af2acff-68e0-4913-846e-f9b904e6bf02"),
                            Discount = 0m,
                            FIO = "Павлов Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("e0bd28b1-e495-41e1-8888-098eba8d927d"),
                            Discount = 0m,
                            FIO = "Андреев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("7546af60-7c85-452d-95d1-d393ed4adf05"),
                            Discount = 0m,
                            FIO = "Макаров Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("79c4e5c0-b126-4e97-bb58-98b9a90a1c94"),
                            Discount = 0m,
                            FIO = "Николаев Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("ffac6a60-49be-45fe-aedc-b91939658058"),
                            Discount = 0m,
                            FIO = "Орлов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("93c44847-317e-45fa-9467-78567e2eea59"),
                            Discount = 0m,
                            FIO = "Алексеев Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("bd519fc7-7510-4cf6-9387-0c93f271a55e"),
                            Discount = 0m,
                            FIO = "Сергеев Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("2f8bdb62-2c31-4baa-86b2-2eeed74abc78"),
                            Discount = 0m,
                            FIO = "Дмитриев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("9f9f9231-7905-4ce4-bf8a-c74b97d95f94"),
                            Discount = 0m,
                            FIO = "Егоров Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("98a64158-9f68-452a-9d1b-642886680e8f"),
                            Discount = 0m,
                            FIO = "Кузнецов Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("fa60f85f-e7c1-433e-b19c-3e7f033afda3"),
                            Discount = 0m,
                            FIO = "Борисов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("ea3a8711-adec-4718-ab5f-953271361ad0"),
                            Discount = 0m,
                            FIO = "Соловьев Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("811c4aae-3e74-43c9-8838-f84214d0e96f"),
                            Discount = 0m,
                            FIO = "Комаров Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("cf729368-9b75-43f2-814c-2ebef2c46351"),
                            Discount = 0m,
                            FIO = "Белов Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("db3959eb-6d96-4dd3-b4c1-3358796c7465"),
                            Discount = 0m,
                            FIO = "Филиппов Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("bda25231-388f-4f7a-93ae-2d41347ed241"),
                            Discount = 0m,
                            FIO = "Матвеев Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        });
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.HasOne("WebApi.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Models.OrderProducts", b =>
                {
                    b.HasOne("WebApi.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.HasOne("WebApi.Models.TypeProduct", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeProduct");
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.TypeProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
