// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi;

#nullable disable

namespace WebApiMigrations
{
    [DbContext(typeof(Context))]
    [Migration("20241009220416_startedDateUpdateV3")]
    partial class startedDateUpdateV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fe84a6b-6f8a-4748-9cb7-0dfa0790414e"),
                            Created = new DateTime(2024, 10, 28, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1636),
                            Description = "Выставка представляет работы современных художников, посвященные теме абстракции.",
                            Title = "Выставка современного искусства 'Абстракция'"
                        },
                        new
                        {
                            Id = new Guid("40648d8b-8165-421c-b5fd-1a7b7820e3cc"),
                            Created = new DateTime(2024, 11, 5, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1672),
                            Description = "Конкурс открыт для художников со всего мира. Прием работ до 15 октября.",
                            Title = "Международный конкурс 'Живопись 2023'"
                        },
                        new
                        {
                            Id = new Guid("bc87df8b-23d5-4ba5-800a-04c93db1afd1"),
                            Created = new DateTime(2024, 10, 26, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1675),
                            Description = "Выставка посвящена искусству XX века, включая работы известных мастеров.",
                            Title = "Выставка 'Искусство XX века'"
                        },
                        new
                        {
                            Id = new Guid("ad469ac4-782e-443a-a345-90342d7ca37c"),
                            Created = new DateTime(2024, 11, 2, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1678),
                            Description = "Конкурс для молодых художников до 30 лет. Прием работ до 30 ноября.",
                            Title = "Конкурс 'Молодое искусство'"
                        },
                        new
                        {
                            Id = new Guid("0585064b-1897-4279-8584-21eec028e4ee"),
                            Created = new DateTime(2024, 10, 12, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1681),
                            Description = "Выставка фотографий, демонстрирующих фотографию как самостоятельное искусство.",
                            Title = "Выставка 'Фотография как искусство'"
                        },
                        new
                        {
                            Id = new Guid("3aa693a5-555c-48a5-bb3e-1654489b725b"),
                            Created = new DateTime(2024, 10, 11, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1686),
                            Description = "Конкурс посвящен графике и рисункам. Прием работ до 20 декабря.",
                            Title = "Конкурс 'Графика и рисунки'"
                        },
                        new
                        {
                            Id = new Guid("7cca5697-1bc9-4e3d-b197-86c1d425abcf"),
                            Created = new DateTime(2024, 10, 23, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1689),
                            Description = "Выставка работ художников из стран Востока, представляющих традиционное и современное искусство.",
                            Title = "Выставка 'Искусство Востока'"
                        },
                        new
                        {
                            Id = new Guid("0d4656a5-1bc2-449c-93f7-4bb76dfe248b"),
                            Created = new DateTime(2024, 11, 7, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1692),
                            Description = "Конкурс для скульпторов и художников, работающих в области пластики. Прием работ до 10 января.",
                            Title = "Конкурс 'Скульптура и пластика'"
                        },
                        new
                        {
                            Id = new Guid("e540c01f-9eae-40a7-9680-4321b2157867"),
                            Created = new DateTime(2024, 11, 3, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1695),
                            Description = "Выставка, демонстрирующая взаимодействие искусства и современных технологий.",
                            Title = "Выставка 'Искусство и технологии'"
                        },
                        new
                        {
                            Id = new Guid("0bff72e1-e5e9-4f45-9384-3cb1a66549d1"),
                            Created = new DateTime(2024, 10, 22, 22, 4, 15, 489, DateTimeKind.Utc).AddTicks(1702),
                            Description = "Конкурс для детских художников до 12 лет. Прием работ до 1 февраля.",
                            Title = "Конкурс 'Искусство для детей'"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Sum")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b25f053b-e25a-4336-8ac3-61c6fd3e8bb2"),
                            Sum = 0m,
                            UserId = new Guid("0624610f-5328-4031-917a-7cbab13aef2a")
                        },
                        new
                        {
                            Id = new Guid("58fd8d05-0977-4b76-826c-3be682edf72c"),
                            Sum = 0m,
                            UserId = new Guid("e220796c-1e69-45ad-b7b8-2703fb4311e7")
                        },
                        new
                        {
                            Id = new Guid("e5db2dfd-b6d8-477f-971c-2344b3a36efd"),
                            Sum = 0m,
                            UserId = new Guid("43dd2077-331d-40fd-94fb-ade6162034f4")
                        },
                        new
                        {
                            Id = new Guid("f58a4811-85e0-4110-9cbc-06172ab10395"),
                            Sum = 0m,
                            UserId = new Guid("26850ef6-41c5-459a-a65c-c24fc614b34f")
                        },
                        new
                        {
                            Id = new Guid("8062754b-ac45-4fda-bcb5-744371d6bdc3"),
                            Sum = 0m,
                            UserId = new Guid("1946b329-421c-4b15-b568-9bf3119c1f1b")
                        },
                        new
                        {
                            Id = new Guid("b623868e-855e-497a-b0e2-622acd4a9042"),
                            Sum = 0m,
                            UserId = new Guid("a71e29f2-e471-4543-a26d-d3cd12cb855a")
                        },
                        new
                        {
                            Id = new Guid("fec4789d-1b7e-4f90-b6ac-cfd5ae9aefad"),
                            Sum = 0m,
                            UserId = new Guid("162c8f6d-8338-43a1-bc84-287bac130d12")
                        },
                        new
                        {
                            Id = new Guid("b253aee2-7d4c-4ba1-9268-8fc37794b99e"),
                            Sum = 0m,
                            UserId = new Guid("1d9a4f5d-e1d9-4ffb-9bac-9ce326b0d5af")
                        },
                        new
                        {
                            Id = new Guid("43c08780-a723-4b0a-95cd-ac9583bd6f8f"),
                            Sum = 0m,
                            UserId = new Guid("5af78c8b-2e16-4658-b00a-007be62424cc")
                        },
                        new
                        {
                            Id = new Guid("3baf39c5-f284-4ac7-8374-e5711cfb04a5"),
                            Sum = 0m,
                            UserId = new Guid("5d409dc9-763f-4ea4-8e94-3ba76dc886ae")
                        },
                        new
                        {
                            Id = new Guid("a165c982-4ea8-4c8d-8fdd-76368c86dc21"),
                            Sum = 0m,
                            UserId = new Guid("ce705f63-720e-4d3f-a6d0-e42ced0a1469")
                        });
                });

            modelBuilder.Entity("WebApi.Models.OrderProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb49c797-b5a9-4286-b1fc-8665c4533603"),
                            Count = 0,
                            Name = "Цифровой арт \"Далекое будущее\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("9de68a4e-0c80-4d7b-8ce7-2836bd75096d"),
                            Count = 0,
                            Name = "Видеоурок \"Как сделать первый 3D дизайн\"",
                            Price = 2000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("7f316017-7080-4162-9b6a-e33f326e9b38"),
                            Count = 0,
                            Name = "Курс \"Художник за месяц\"",
                            Price = 6000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("c3f9bc6a-9285-455f-a6ef-ff40165ef981"),
                            Count = 0,
                            Name = "Песня, сгенерированная нейросетью",
                            Price = 100m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("5336dafc-0b8d-4323-a28d-2005c662fa29"),
                            Count = 0,
                            Name = "Цифровой арт \"Цифровое искусство\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("2aac3e55-0a2a-4be0-8489-665258e591cd"),
                            Count = 0,
                            Name = "Видеоурок \"Песня \"Ромашки\" на гитаре\"",
                            Price = 2000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("a560fcd3-3782-4958-87fe-f72862272c18"),
                            Count = 0,
                            Name = "Цифровой арт \"Красивый город\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("33a51587-f0dd-4aad-ad98-68bfea744ce4"),
                            Count = 0,
                            Name = "Реклама",
                            Price = 10000m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("240af5a4-6101-45eb-809f-5491b75ef970"),
                            Count = 0,
                            Name = "Помощь с идеей для вашего проекта",
                            Price = 500m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("2d402b80-7440-40fa-8905-cc7053ecdec9"),
                            Count = 0,
                            Name = "Онлайн урок по рисованию",
                            Price = 1900m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("81cb76d3-e683-4ee3-9866-9466fbc32997"),
                            Count = 0,
                            Name = "Цифровой арт \"Ночной город\"",
                            Price = 3500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("29730f5f-efbc-4c40-b5e2-50f5c838f6bc"),
                            Count = 0,
                            Name = "Видеоурок \"Основы 3D моделирования\"",
                            Price = 2500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("6d6856d0-1cd9-45ac-a77b-bdf0d319e092"),
                            Count = 0,
                            Name = "Курс \"Графика в игре\"",
                            Price = 4500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("24b3225b-62ac-40fe-bd0b-1ab10b760803"),
                            Count = 0,
                            Name = "Песня, сгенерированная нейросетью \"Весна\"",
                            Price = 150m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("6db310a6-c70c-4be3-b858-d1eeaea37457"),
                            Count = 0,
                            Name = "Цифровой арт \"Закат на пляже\"",
                            Price = 4000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("a02e4ad1-a9f5-4b99-923b-df09483cf0d0"),
                            Count = 0,
                            Name = "Курс \"3D анимация\"",
                            Price = 6000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("9c41aff6-8bb3-4682-9dc0-ac4fc48458f2"),
                            Count = 0,
                            Name = "Цифровой арт \"Летний день\"",
                            Price = 2000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("6fffb46f-bf2f-4e63-b2ad-3ea3da940ece"),
                            Count = 0,
                            Name = "Видеоурок \"Рисование в Photoshop\"",
                            Price = 1500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("b1444211-97c8-4b09-ad3d-911c936a0444"),
                            Count = 0,
                            Name = "Цифровой арт \"Зимний лес\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("275f03fa-3a9e-4dda-b691-2652738734b7"),
                            Count = 0,
                            Name = "Видеоурок \"Рисование портретов\"",
                            Price = 3000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("5e91009a-7a44-43e4-b510-4adad4f6ff66"),
                            Count = 1,
                            Name = "Курс \"2D анимация\"",
                            Price = 4000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("c2bc2461-2355-4ec4-92d4-23de2bf81883"),
                            Count = 1,
                            Name = "Цифровой арт \"Городской пейзаж\"",
                            Price = 2500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("bf1ab1a3-f3dd-4708-82c5-b4390eb9ae1c"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Procreate\"",
                            Price = 3500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("5492760d-7c1c-4fa3-b797-5ab07849abaa"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с водопадом\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("f54678df-6c42-42e3-8ab3-3f0faccff11d"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Illustrator\"",
                            Price = 2000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("835c17f3-e2f2-4f6f-806e-cf73578bc5b4"),
                            Count = 1,
                            Name = "Курс \"3D моделирование\"",
                            Price = 4500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("a0386209-348a-4f5c-ab1e-98ed798caa1a"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с горами\"",
                            Price = 3000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("55ef267d-c59c-4271-bce9-355ef9c135e3"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с озером\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("76d51a18-000e-435f-856e-de51bed5d9d1"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Sketchbook\"",
                            Price = 3000m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("51b7dc1d-a4f5-4b19-a697-8be253de2752"),
                            Count = 1,
                            Name = "Курс \"2D игровая графика\"",
                            Price = 4000m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("782752fe-debc-4f01-8d95-eda33d1a1915"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с лесом\"",
                            Price = 2500m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("e8b1d2a0-34e6-486f-a138-9b811a00b5c5"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Affinity Designer\"",
                            Price = 3500m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("65b035d3-229f-4c9a-8318-c0707f2f0687"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с морем\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("204c9e90-cd1b-4437-a3ae-0633d1904191"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в Krita\"",
                            Price = 2000m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("0231531e-cbda-416c-b842-b8bde9acce79"),
                            Count = 1,
                            Name = "Курс \"3D игровая графика\"",
                            Price = 4500m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("5ba66e0b-0e7d-443e-80ec-501660344535"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с пустыней\"",
                            Price = 3000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        },
                        new
                        {
                            Id = new Guid("b27418d2-8ea3-4336-88d8-a3a0784ff5c5"),
                            Count = 1,
                            Name = "Видеоурок \"Рисование в PaintTool SAI\"",
                            Price = 2500m,
                            TypeId = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab")
                        },
                        new
                        {
                            Id = new Guid("67a8abcc-30bc-4406-8d91-c628f4e010fd"),
                            Count = 1,
                            Name = "Цифровой арт \"Пейзаж с вулканом\"",
                            Price = 5000m,
                            TypeId = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635")
                        });
                });

            modelBuilder.Entity("WebApi.Models.TypeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8f9b99f-810b-442e-b54c-366f4e802635"),
                            Name = "Товар"
                        },
                        new
                        {
                            Id = new Guid("a7151783-8922-42ae-a0c7-acc4125c35ab"),
                            Name = "Услуга"
                        });
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClient")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvider")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0624610f-5328-4031-917a-7cbab13aef2a"),
                            Discount = 0m,
                            FIO = "Юриков Дмитрий Александрович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("e220796c-1e69-45ad-b7b8-2703fb4311e7"),
                            Discount = 0m,
                            FIO = "Иванов Сергей Максимович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("43dd2077-331d-40fd-94fb-ade6162034f4"),
                            Discount = 0m,
                            FIO = "Петров Алексей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("26850ef6-41c5-459a-a65c-c24fc614b34f"),
                            Discount = 0m,
                            FIO = "Сидоров Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("1946b329-421c-4b15-b568-9bf3119c1f1b"),
                            Discount = 0m,
                            FIO = "Морозов Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("a71e29f2-e471-4543-a26d-d3cd12cb855a"),
                            Discount = 0m,
                            FIO = "Васильев Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("162c8f6d-8338-43a1-bc84-287bac130d12"),
                            Discount = 0m,
                            FIO = "Козлов Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("1d9a4f5d-e1d9-4ffb-9bac-9ce326b0d5af"),
                            Discount = 0m,
                            FIO = "Новиков Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("5af78c8b-2e16-4658-b00a-007be62424cc"),
                            Discount = 0m,
                            FIO = "Соколов Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("5d409dc9-763f-4ea4-8e94-3ba76dc886ae"),
                            Discount = 0m,
                            FIO = "Михайлов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("ce705f63-720e-4d3f-a6d0-e42ced0a1469"),
                            Discount = 0m,
                            FIO = "Федоров Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("6234efdd-7e0d-4960-a6f2-5790f9c3eaa2"),
                            Discount = 0m,
                            FIO = "Попов Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("76e2296f-9e00-413f-810e-5c36efa8ab81"),
                            Discount = 0m,
                            FIO = "Лебедев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("e1d9326d-443c-4fa1-a680-1fdcdb1c2ce7"),
                            Discount = 0m,
                            FIO = "Ковалев Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("1a24319d-c152-44a2-8e56-f4634dd8f806"),
                            Discount = 0m,
                            FIO = "Ильин Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("2f1181a8-00dd-4ab1-917c-7b91c524d5da"),
                            Discount = 0m,
                            FIO = "Григорьев Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("77841083-0886-4650-a566-ff0373016690"),
                            Discount = 0m,
                            FIO = "Семенов Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("1e200f3e-59bc-4df4-8530-05e4b910f909"),
                            Discount = 0m,
                            FIO = "Павлов Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("bd793179-0438-4543-ad2e-dc0adefe595b"),
                            Discount = 0m,
                            FIO = "Андреев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("7fcdb4aa-41e6-4cd1-b68e-cca514a45b0e"),
                            Discount = 0m,
                            FIO = "Макаров Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("695ea249-6811-46e6-a75c-9651fdda0078"),
                            Discount = 0m,
                            FIO = "Николаев Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("9b59c903-c56f-41ef-b251-1eeaff61aa95"),
                            Discount = 0m,
                            FIO = "Орлов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("81273bbb-b01c-4021-8130-3cdeda08680d"),
                            Discount = 0m,
                            FIO = "Алексеев Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("6f822fd4-a732-436c-a1c9-3ff027af4c1c"),
                            Discount = 0m,
                            FIO = "Сергеев Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("3fe7d971-d151-4473-ab37-488137be1a95"),
                            Discount = 0m,
                            FIO = "Дмитриев Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("e4a4c953-eae2-47fe-a46a-eccacab63664"),
                            Discount = 0m,
                            FIO = "Егоров Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("4080739a-5f17-4923-9434-6d703fdc4283"),
                            Discount = 0m,
                            FIO = "Кузнецов Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("70d23143-4e89-4b4f-b081-aa9181fb4cc8"),
                            Discount = 0m,
                            FIO = "Борисов Иван Сергеевич",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("ab84e037-7581-46f3-bdf7-6d1dd7bc724f"),
                            Discount = 0m,
                            FIO = "Соловьев Андрей Николаевич",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("55141aa4-3bcf-4bae-8cb5-40f9cbe4a3c0"),
                            Discount = 0m,
                            FIO = "Комаров Константин Петрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("4436a233-0afb-4f39-b429-434a41150770"),
                            Discount = 0m,
                            FIO = "Белов Максим Иванович",
                            IsClient = true,
                            IsProvider = false
                        },
                        new
                        {
                            Id = new Guid("143526d3-7ab5-4336-9012-6b81111e90e2"),
                            Discount = 0m,
                            FIO = "Филиппов Дмитрий Александрович",
                            IsClient = false,
                            IsProvider = true
                        },
                        new
                        {
                            Id = new Guid("2a7652c4-9c01-436a-9d35-b49c5d5b0fc8"),
                            Discount = 0m,
                            FIO = "Матвеев Сергей Дмитриевич",
                            IsClient = true,
                            IsProvider = false
                        });
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.HasOne("WebApi.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Models.OrderProducts", b =>
                {
                    b.HasOne("WebApi.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.HasOne("WebApi.Models.TypeProduct", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeProduct");
                });

            modelBuilder.Entity("WebApi.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Models.TypeProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
